### GENERAL SETTINGS ###

# Site settings
title: AppFlush
description: "AppFlush Description"
author: "AppFlush"
baseurl: "" #important: start with /
url: "http://appflush.com"
#pygments: true
#highlighter: pygments

# Build settings
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#3D91CC" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
#  - title: facebook
#    url: https://www.facebook.com/profile.php?id=100008409195050
  - title: twitter
    url: https://twitter.com/Appflushs

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Planet Earth Earth-Moon System Solar System
    - Milky Way Galaxy Local Group Virgo Supercluster
    - Observable Universe

email: support@appflush.com
tel: +82 0000-0000